Repository the-spot-campus/MatzipBook-Server, pull requests merged in 2025-05, with the labels that each got.

#2 Chore/#1 초기 프로젝트 세팅
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/matzipbookserver/MatzipbookServerApplication.java
  src/main/java/com/example/matzipbookserver/global/exception/ApiExceptionHandler.java
  src/main/java/com/example/matzipbookserver/global/exception/RestApiException.java
  src/main/java/com/example/matzipbookserver/global/response/CustomResponseDto.java
  src/main/java/com/example/matzipbookserver/global/response/SuccessResponse.java
  src/main/java/com/example/matzipbookserver/global/response/error/ErrorCode.java
  src/main/java/com/example/matzipbookserver/global/response/success/SuccessCode.java
  src/main/resources/application.properties
  src/test/java/com/example/matzipbookserver/MatzipbookServerApplicationTests.java
Labels: 🔗 chore, 🌟 feat

#11 Chore/#5 Dockerfile 및 CI/CD 파이프라인 구성
  .github/workflows/ec2-pipeline.yml
  .github/workflows/test-pipeline.yml
  Dockerfile
  build.gradle
  src/docs/asciidoc/auth.adoc
  src/main/java/com/example/matzipbookserver/global/response/CustomResponseDto.java
  src/main/java/com/example/matzipbookserver/global/response/SuccessResponse.java
Labels: 🔗 chore, 🌏 server

#9 Feat/#3 가게 상세 조회
  .gitignore
  build.gradle
  src/main/java/com/example/matzipbookserver/MatzipbookServerApplication.java
  src/main/java/com/example/matzipbookserver/global/config/KakaoFeignConfig.java
  src/main/java/com/example/matzipbookserver/global/response/error/StoreErrorCode.java
  src/main/java/com/example/matzipbookserver/global/response/success/StoreSuccessCode.java
  src/main/java/com/example/matzipbookserver/store/controller/StoreController.java
  src/main/java/com/example/matzipbookserver/store/controller/dto/StoreResponseDto.java
  src/main/java/com/example/matzipbookserver/store/domain/Store.java
  src/main/java/com/example/matzipbookserver/store/domain/repository/StoreRepository.java
  src/main/java/com/example/matzipbookserver/store/external/KakaoLocalClient.java
  src/main/java/com/example/matzipbookserver/store/external/dto/KakaoDocument.java
  src/main/java/com/example/matzipbookserver/store/external/dto/KakaoMeta.java
  src/main/java/com/example/matzipbookserver/store/external/dto/KakaoSearchResponse.java
  src/main/java/com/example/matzipbookserver/store/service/StoreService.java
Labels: 🌟 feat

#8 Feat/#6 카카오/애플 소셜 로그인
  .gitignore
  build.gradle
  src/main/java/com/example/matzipbookserver/global/config/RestTemplateConfig.java
  src/main/java/com/example/matzipbookserver/global/response/error/AuthErrorCode.java
  src/main/java/com/example/matzipbookserver/global/response/success/MemberSuccessCode.java
  src/main/java/com/example/matzipbookserver/member/controller/AuthController.java
  src/main/java/com/example/matzipbookserver/member/controller/dto/request/AppleLoginRequest.java
  src/main/java/com/example/matzipbookserver/member/controller/dto/request/FcmTokenRequest.java
  src/main/java/com/example/matzipbookserver/member/controller/dto/request/KakaoLoginRequest.java
  src/main/java/com/example/matzipbookserver/member/controller/dto/response/AppleLoginResponse.java
  src/main/java/com/example/matzipbookserver/member/controller/dto/response/KakaoLoginResponse.java
  src/main/java/com/example/matzipbookserver/member/controller/dto/response/LoginResponse.java
  src/main/java/com/example/matzipbookserver/member/controller/dto/response/SignupNeededResponse.java
  src/main/java/com/example/matzipbookserver/member/domain/FcmToken.java
  src/main/java/com/example/matzipbookserver/member/domain/Member.java
  src/main/java/com/example/matzipbookserver/member/repository/FcmTokenRepository.java
  src/main/java/com/example/matzipbookserver/member/repository/MemberRepository.java
  src/main/java/com/example/matzipbookserver/member/service/AuthService.java
  src/main/java/com/example/matzipbookserver/member/service/FcmTokenService.java
  src/main/java/com/example/matzipbookserver/member/service/JwtTokenProvider.java
  src/main/java/com/example/matzipbookserver/member/util/AppleOAuthUtil.java
  src/main/java/com/example/matzipbookserver/member/util/KakaoOAuthUtil.java
  src/main/java/com/example/matzipbookserver/member/util/dto/AppleIdTokenPayload.java
  src/main/java/com/example/matzipbookserver/member/util/dto/AppleTokenResponse.java
  src/main/java/com/example/matzipbookserver/member/util/dto/KakaoTokenDTO.java
  src/main/java/com/example/matzipbookserver/member/util/dto/KakaoUserDTO.java
  src/test/java/com/example/matzipbookserver/member/controller/AuthControllerTest.java
Labels: 🌟 feat
